## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [2]:
#Do your imports here
import numpy as np

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [3]:
# okay numpy is great but... how would you inverse a matrix by hand?

#We take the matrix and do diagonal 1 matrix besides it so a [[1,0,0],[0,1,0],[0,0,1]]
# then we change the matrix till its looks like the diagonal matrix. 
#The changes on the right diagonal matrix is at the end the new inverted matrix

a = np.array([[3,1,2], [-5,4,1], [0,3,-8]])

def inverse_matrix(A):
    return np.linalg.inv(A)

In [4]:
b = np.array([[1., 2.], [3., 4.]])
inverse_matrix(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [4]:
# Just answer using code --> easy stuff!

A = np.array([[3, 0.6, 4, -3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3, -5.76, 45, 0],[2, -2, 1.3 , 9],[-9, 0,0,0]])
C = np.array([[0,1009, -66.7849, 90],[0,5,4,-0.07],[-7.7,0,0,0]])

D = A + B - C
print(D)

print(D[1,2])
print(D[2,0])

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed.

np.linalg.solve(a,b)

[[ 6.000000e+00 -1.014160e+03  1.157849e+02 -9.300000e+01]
 [ 7.000000e-01 -3.000000e+00 -2.700000e+00  1.767000e+01]
 [ 5.700000e+00  0.000000e+00 -8.000000e+00  6.000000e-03]]
-2.7
5.7


TypeError: _solve_dispatcher() takes 2 positional arguments but 3 were given

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [15]:
AA = np.array([0.6,-15,2,5,98])
BB = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

CC = np.dot(AA.T, BB)
CC

array([-102.8,  255.2,  595.6])

In [16]:
CC[2]

595.6