# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [45]:
np.__version__

'1.19.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [12]:
arr = np.array([1,2,3])

print("Size of the array: ", 
      arr.size) 
print("Memory size of one array element in bytes: ", 
      arr.itemsize) 
print("Memory size of numpy array in bytes:", 
      arr.size * arr.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [17]:
#%run `python -c "import numpy; http://numpy.info(numpy.add)"`
#Open Anaconda Prompt #python #import numpy #help(numpy.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
arr = np.zeros(10)
print(arr)
arr[4]=1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [46]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [32]:
arr=np.arange(1,10)
print(arr)
arr = arr[::-1]
print(arr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [47]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [48]:
arr=np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [51]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [53]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.12310841 0.62650617 0.9200822 ]
  [0.25010177 0.85746649 0.2338694 ]
  [0.94060259 0.61407551 0.80499101]]

 [[0.17133912 0.9853519  0.42425833]
  [0.81753783 0.50821638 0.29301714]
  [0.44600816 0.0732354  0.4972983 ]]

 [[0.06224481 0.33754775 0.33884085]
  [0.66471636 0.15506435 0.47746702]
  [0.16825191 0.84462453 0.67616243]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [58]:
arr = np.random.random(size=(10,10))
print(arr)
print(np.max(arr))
print(np.min(arr))

[[0.00710016 0.45250374 0.2262509  0.04063101 0.04032307 0.4058634
  0.08379886 0.96466067 0.62433155 0.08906979]
 [0.90513259 0.69117141 0.84515192 0.27912954 0.96045715 0.85555582
  0.24958291 0.48408838 0.37476832 0.20950154]
 [0.85988768 0.03510176 0.20782472 0.12354363 0.07373148 0.11161967
  0.15031605 0.92509575 0.67532178 0.25653889]
 [0.05415933 0.05964671 0.46502831 0.10228595 0.06894621 0.95421324
  0.84330047 0.79028245 0.27762744 0.60574638]
 [0.3322603  0.72663767 0.01643401 0.10011839 0.87833658 0.87251096
  0.38369947 0.5143355  0.900631   0.9490346 ]
 [0.91141316 0.3586588  0.77061782 0.92120544 0.22729561 0.39097229
  0.92044353 0.55764229 0.80902514 0.24134523]
 [0.86369888 0.62544269 0.91797269 0.51823887 0.36068715 0.79753474
  0.62425075 0.83920887 0.62784376 0.05634203]
 [0.20009688 0.01689864 0.64540411 0.88831417 0.73907095 0.84433905
  0.92391294 0.17225    0.56446621 0.08083113]
 [0.25099495 0.87300233 0.65644348 0.53531814 0.60254373 0.91765024
  0.06263582 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [64]:
arr = np.random.rand(30)
print(arr.mean())

0.4748614977623813


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [55]:
arr = np.array([[0,0,0],[0,1,0],[0,0,0]])
print(arr)
arr.shape

[[0 0 0]
 [0 1 0]
 [0 0 0]]


(3, 3)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [70]:
arr = np.ones((3,3))
print(arr)
arr = np.pad(arr, pad_width=1 , mode='constant',constant_values=0) #Number of values padded to the edges of each axis #constant_values is the input
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [71]:
print(0 * np.nan)
print(np.nan == np.nan) #why is this false ?
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [91]:
arr = np.arange(1,5)
print(arr)
arr = np.diag(arr, k=-1) #construct a diagonal array 
print(arr)               #k<0 for diagonals below the main diagonal
                           

[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [95]:
arr = np.zeros((8,8),dtype=int)
print(arr)

arr[1::2,::2] = 1 #The additional syntax of a[x::y] means get every yth element starting at position x
print(arr)        # [for list(row),for element in list]

arr[::2,1::2] = 1
print(arr)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [110]:
#arr = np.arange(336) 
#print(arr)
#newarr = arr.reshape(6,7,8)
#print(newarr)
print(np.unravel_index(100,(6,7,8))) # Converts a flat index or array of flat indices into a tuple of coordinate arrays.

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [118]:
arr = np.array([0, 1, 0, 1, 0, 1, 0, 1, 1 ,0, 1, 0, 1, 0, 1, 0]) #need the pattern of 16 elements
print(arr)
arr = np.tile(arr,4) #takes input and repeats it, n - times
print(arr)
arr = arr.reshape(8,8) # reshape to 8*8
print(arr)

[0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0
 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [125]:
arr = np.arange(25)
arr = arr.reshape(5,5)
print(arr)
arr = arr - arr.mean() #You first subtract the mean to center it around 0
arr = arr / arr.max()  #then divide by the max to scale it to [−1,1]
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-1.         -0.91666667 -0.83333333 -0.75       -0.66666667]
 [-0.58333333 -0.5        -0.41666667 -0.33333333 -0.25      ]
 [-0.16666667 -0.08333333  0.          0.08333333  0.16666667]
 [ 0.25        0.33333333  0.41666667  0.5         0.58333333]
 [ 0.66666667  0.75        0.83333333  0.91666667  1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [136]:
color = np.dtype([("r", np.ubyte, 1), # really weird solution i found
                  ("g", np.ubyte, 1), # dtype structured data type
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-136-bef8a1b285fe>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1), # really weird solution i found


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [140]:
arr1 = np.random.rand(5,3)
#print(arr1)
arr2 = np.random.rand(3,2)
#print(arr2)
arr3 = np.dot(arr1,arr2) # np.dot(array, array)
print(arr3)

[[0.58094907 0.12175057]
 [0.55426234 0.62412534]
 [0.73809684 0.97439769]
 [0.49895737 0.67139148]
 [0.1084439  0.18331997]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [144]:
arr = np.arange(20)
print(arr)
negate = (arr > 2) & (arr < 8)
arr[negate] *= -1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2 -3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *      #didnt execute it to not change anything
print(sum(range(5),-1))

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [150]:
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z) # only one whats not legal

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [159]:
print(np.array(0) / np.array(0)) # result = nan
print(np.array(0) // np.array(0)) #result = 0
print(np.array([np.nan]).astype(int).astype(float)) #result = array([-9.22337204e+18])

nan
0
[-9.22337204e+18]


<ipython-input-159-03ff11a1b93e>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0)) # result = nan
<ipython-input-159-03ff11a1b93e>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) #result = 0


#### 29. How to round away from zero a float array ? (★☆☆)

In [187]:
arr = np.random.rand(5,5)
print(arr)
print(np.around(arr)) # its not roundign up 
print(np.copysign(np.ceil(abs(arr)),arr)) # first take absolut, ceil rounding up, copysign to make it negative negative again

[[0.68745702 0.16767056 0.71823426 0.98331668 0.42873519]
 [0.89313665 0.40134276 0.91849508 0.70094825 0.96010028]
 [0.08859408 0.61417359 0.3433445  0.93540558 0.12493141]
 [0.27836819 0.54439108 0.29819769 0.12658836 0.81162311]
 [0.45277904 0.05415317 0.37045945 0.8122074  0.279984  ]]
[[1. 0. 1. 1. 0.]
 [1. 0. 1. 1. 1.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [169]:
arr1= np.arange(1,9)
print(arr1)
arr2 = np.arange(8,18)
print(arr2)
same_value = np.intersect1d(arr1,arr2) #Common values between two arrays
print(same_value)

[1 2 3 4 5 6 7 8]
[ 8  9 10 11 12 13 14 15 16 17]
[8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
warnings.filterwarnings('ignore') 

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [170]:
np.sqrt(-1) == np.emath.sqrt(-1) # False

<ipython-input-170-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [179]:
date_today = np.datetime64('today')
print(date_today)
date_yesterday = np.datetime64('today') - np.timedelta64(1)
print(date_yesterday)
date_tomorrow = np.datetime64('today') + np.timedelta64(1)
print(date_tomorrow)

2021-03-22
2021-03-21
2021-03-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print('July, 2016')
print(np.arange('2016-06','2016-07',dtype='datetime64[D]'))

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [183]:
A = np.ones((3,3))
B = np.ones((3,3))
print(A)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [205]:
arr = np.random.randint(1,10,10)

print(arr)
print(arr - arr%1) # its just a array with 0 in it 
print(arr + arr%1) # its just a array with 0 in it 
print(np.floor(arr)) #Return the floor of the input, element-wise.
print(arr.astype(int)) #Return type as int
print(np.rint(arr)) #Round elements of the array to the nearest integer.
print(np.ceil(arr)) #Return the ceiling of the input, element-wise.
print(np.trunc(arr)) #Return the truncated value of the input, element-wise.


[9 7 9 3 9 8 3 4 6 3]
[9 7 9 3 9 8 3 4 6 3]
[9 7 9 3 9 8 3 4 6 3]
[9. 7. 9. 3. 9. 8. 3. 4. 6. 3.]
[9 7 9 3 9 8 3 4 6 3]
[9. 7. 9. 3. 9. 8. 3. 4. 6. 3.]
[9. 7. 9. 3. 9. 8. 3. 4. 6. 3.]
[9. 7. 9. 3. 9. 8. 3. 4. 6. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [206]:
arr = np.random.randint(0,4,25).reshape(5,5)
print(arr)

[[2 1 3 0 1]
 [3 3 2 3 0]
 [2 3 3 2 2]
 [2 3 1 3 0]
 [2 1 3 2 0]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [207]:
def generator_function(max_value):
    arr = np.random.randint(0,max_value,10)
    return arr

generator_function(100)

array([45, 21, 26,  2, 51, 51, 58, 34, 66, 92])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [208]:
arr = np.random.random(10)
print(arr)

[0.04581926 0.88696524 0.72438217 0.42192123 0.73353428 0.22457888
 0.30927322 0.00753817 0.35297158 0.98432067]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [215]:
arr = np.random.randint(0,4,10)
print(arr)
arr = np.sort(arr)
print(arr)

[3 2 3 2 1 2 0 0 2 1]
[0 0 1 1 2 2 2 2 3 3]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [217]:
arr = np.random.randint(0,4,25)
print(arr)
%timeit np.sum(arr)
%timeit np.add.reduce(arr) #Reduces array’s dimension by one, by applying ufunc along one axis.

[2 2 0 1 3 2 3 0 3 2 2 2 3 0 2 1 1 3 3 1 2 1 0 1 1]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [220]:
arr1 = np.random.normal(size=(1,2))
print(arr1)
arr2 = np.random.normal(size=(1,2))
print(arr2)
print((arr1 == arr2).all())

[[-0.71093427 -1.03658023]]
[[1.39742627 1.09388237]]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [219]:
arr = np.random.randint(0,4,25)
print(arr)
arr.setflags(write=False)
arr[0] =1 

[2 1 1 3 3 1 1 3 1 1 2 0 1 3 1 3 3 3 2 2 2 0 0 2 0]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [229]:
arr = np.random.random((10,2))
print(arr)
x = arr[:,0]
#print(x)
y = arr[:,1]
#print(y)
r = np.sqrt(x**2+y**2)
print(r)
t = np.arctan2(y,x)
print(t)

[[0.15452196 0.25515452]
 [0.3222928  0.08132892]
 [0.07367162 0.56058328]
 [0.82202318 0.11712476]
 [0.24030283 0.08964999]
 [0.1396116  0.21918611]
 [0.7304422  0.37450805]
 [0.97152225 0.988502  ]
 [0.59673074 0.34835935]
 [0.03484723 0.39295159]]
[0.29829661 0.33239591 0.5654035  0.83032543 0.25648113 0.25987295
 0.82085449 1.38599844 0.69097165 0.3944937 ]
[1.02626825 0.24718433 1.44012558 0.14153089 0.35707833 1.00364661
 0.47376712 0.79406098 0.5284075  1.48234699]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [236]:
arr = np.random.random(10)
print(arr)
arr[np.argmax(arr)]=0
print(arr)

[0.50613495 0.98811638 0.01191961 0.72543536 0.32310856 0.98075763
 0.04931929 0.14339425 0.00674779 0.37439512]
[0.50613495 0.         0.01191961 0.72543536 0.32310856 0.98075763
 0.04931929 0.14339425 0.00674779 0.37439512]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [244]:
arr = np.random.random((5,2))
print(arr)
x = arr[:,0]
#print(x)
y = arr[:,1]
#print(y)
print(np.meshgrid(x,y))

[[0.09955734 0.57661537]
 [0.03165071 0.24221164]
 [0.89395121 0.27757491]
 [0.55292134 0.10661542]
 [0.01929968 0.97151139]]
[array([[0.09955734, 0.03165071, 0.89395121, 0.55292134, 0.01929968],
       [0.09955734, 0.03165071, 0.89395121, 0.55292134, 0.01929968],
       [0.09955734, 0.03165071, 0.89395121, 0.55292134, 0.01929968],
       [0.09955734, 0.03165071, 0.89395121, 0.55292134, 0.01929968],
       [0.09955734, 0.03165071, 0.89395121, 0.55292134, 0.01929968]]), array([[0.57661537, 0.57661537, 0.57661537, 0.57661537, 0.57661537],
       [0.24221164, 0.24221164, 0.24221164, 0.24221164, 0.24221164],
       [0.27757491, 0.27757491, 0.27757491, 0.27757491, 0.27757491],
       [0.10661542, 0.10661542, 0.10661542, 0.10661542, 0.10661542],
       [0.97151139, 0.97151139, 0.97151139, 0.97151139, 0.97151139]])]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [259]:
x = np.array([1,2,3,4])
y = np.array([5,6,7])
#cauchy = 1.0/(x.reshape((-1,1))-y) # Cij=cauchy # xi= x.reshape # yj = y
#print(cauchy)                      # if in the arrays same matrix i got a divided by zero ? how to solve issue
c = 1.0/np.subtract.outer(x,y) #Apply the ufunc op to all pairs (a, b) with a in A and b in B.
print(c)                       #subtract it without the need to reshape it because uses matrix math 


[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [281]:
print(np.iinfo(np.int8).min) #iinfo integer info 
print(np.iinfo(np.int8).max)
print(np.iinfo(np.int16).min)
print(np.iinfo(np.int16).max)
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)
print(np.iinfo(np.int64).min)
print(np.iinfo(np.int64).max)
print(np.finfo(np.float32).min) #finfo float info
print(np.finfo(np.float32).max)
print(np.finfo(np.float64).min)
print(np.finfo(np.float64).max)
#96 didnt work 
print(np.finfo(np.float128).min)
print(np.finfo(np.float128).max)
#tried other ones but couldnt found
#uint
#bool
#complex

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308
-1.189731495357231765e+4932
1.189731495357231765e+4932


#### 49. How to print all the values of an array? (★★☆)

In [283]:
arr = np.ones((20,20)) #just normal maybe there is a limit like in google colab ?
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [309]:
vec = np.arange(10)
print(vec)
point = np.random.uniform(0,10)
print(point)
index = (np.abs(vec-point)).argmin() # argmin = Returns the indices of the minimum values along an axis.
print(np.abs(vec-point))
print(index)
print(vec[index])

[0 1 2 3 4 5 6 7 8 9]
9.250832121835913
[9.25083212 8.25083212 7.25083212 6.25083212 5.25083212 4.25083212
 3.25083212 2.25083212 1.25083212 0.25083212]
9
9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[[0,2]] = arr[[2,0]]
print(arr)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [296]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret)
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z,3))

[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 0.  1.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48.
 51. 54.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)