In [3]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[[0,2]] = arr[[2,0]]
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


**75. How to compute averages using a sliding window over an array?**

In [1]:
def moving_average(a, window_size=3):
    sums = np.cumsum(a)
    sums[window_size:] = sums[window_size:] - sums[:-window_size] #??
    return sums[window_size-1:]/window_size 

In [4]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
moving_average(array)

array([2., 3., 4., 5., 6., 7., 8., 9.])